apiVersion: v1
kind: Pod
metadata:
  name: insecure-pod
  labels:
    app: insecure-demo
spec:
  containers:
  - name: nginx
    image: nginx
    ports:
    - containerPort: 80

    securityContext:
      privileged: true
      runAsUser: 0